source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

plugin 'cocoapods-keys', {
    :project => "Artsy_Authentication",
    :target => "ArtsyAuthenticationExample",
    :keys => [
        "ArtsyAPIClientSecret",
        "ArtsyAPIClientKey",
        "ArtsyFacebookAppID",
        "ArtsyTwitterKey",
        "ArtsyTwitterSecret"
]}

target 'ArtsyAuthenticationExample', :exclusive => true do
  pod "Artsy+Authentication", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Artsy+Authentication", :path => "../"

  pod 'Quick'
  pod 'Nimble'
  pod 'OHHTTPStubs'
end
