osx_image: xcode10.1
language: objective-c

before_install:
  - bundle install
  - cd Example ; make keys ; cd ..
before_script:
  - export LANG=en_US.UTF-8
install:
  - cd Example ; make install ; cd ..

xcode_workspace: Example/Artsy_Authentication.xcworkspace
xcode_scheme: Artsy_Authentication-Example
xcode_sdk: iphonesimulator
